general:
  df_path: '../data/csv/raw_test.csv'
  batch_size: 128
  dataloader_workers: 8
  seed: 42
  max_epochs: 100
  cls_save_path: ../cls_tokens_test
  test_data: True

model:
  backbone_model: 'cardiffnlp/twitter-roberta-large-2022-154m'
  save_path: '../saved_models/cardiff-large.ckpt'
  cls_filename: cardiff-large
