general:
  train_path: '/Users/tunaberkalmaci/Downloads/twitter_sentiment_analysis/src/data/processed/raw_processed.csv'
  batch_size: 64
  dataloader_workers: 7
  seed: 42
  use_wandb: True
  max_epochs: 3

model1:
  backbone_model: 'cardiffnlp/twitter-roberta-base-sentiment-latest'
  save_path: '/Users/tunaberkalmaci/Downloads/twitter_sentiment_analysis/src/saved_models/cardiffnlp/twitter-roberta-base-sentiment-latest_linear/epoch=01-val_loss=0.22.ckpt'

model2:
  backbone_model: 'cardiffnlp/twitter-roberta-base-2022-154m'
  save_path: '/Users/tunaberkalmaci/Downloads/twitter_sentiment_analysis/src/saved_models/cardiff-large/epoch=00-step=9375-val_loss=0.25.ckpt'

model3:
  backbone_model: 'vinai/bertweet-large'
  save_path: '/Users/tunaberkalmaci/Downloads/twitter_sentiment_analysis/src/saved_models/vinai_bertweet-large_linear_c3b9c1/epoch=00-step=62500-val_loss=0.23.ckpt'

model4:
  backbone_model: 'vinai/bertweet-base'
  save_path: '/Users/tunaberkalmaci/Downloads/twitter_sentiment_analysis/src/saved_models/vinai_bertweet-base_linear_4b24c8/epoch=00-step=31250-val_loss=0.22.ckpt'


