general:
  df_path: '/home/ubuntu/data/raw_processed.csv'
  batch_size: 128
  dataloader_workers: 8
  seed: 42
  max_epochs: 100
  np_save_path: /home/ubuntu/twitter_sentiment_analysis/src/cls_tokens

model:
  backbone_model: 'cardiffnlp/twitter-roberta-base-sentiment-latest'
  save_path: '/home/ubuntu/saved_models/cardiff-base/epoch=01-val_loss=0.22.ckpt'
  cls_file_name: cardiff-base