general:
  rand_seed: 42
  data_path: '../data/csv/raw_train.csv'
  batch_size: 256
  tweets_column: 'text'
  labels_column: 'labels'
  local: False
  validation_size: 0.2
  reduced_length: 1000
  use_wandb: False
  run_id: bert-base-uncased

model:
  name: 'bert-base-uncased'
  batch_size: 256
  lr: 0.01
  num_epochs: 2
  dropout_prob: 0.2
  max_length: 100
  max_epochs: 5
  base_model_require_grad: False
  dataloader_workers: 7
  use_batchsize_finder: False
  use_lr_finder: False
  use_device_stats: False
  save_name: 'bert-base-uncased'

testing:
  test_input_path: '../data/csv/raw_test.csv'
  model_checkpoint: './saved_models/bert-base-uncased.ckpt'