general:
  rand_seed: 42
  data_path: '../data/csv/raw_train.csv'
  batch_size: 128
  tweets_column: 'text'
  labels_column: 'labels'
  local: False
  validation_size: 0.2
  reduced_length: 100000
  use_wandb: False
  use_model_summary: False
  use_early_stopping: False
  use_swa: False
  use_profiler: False
  run_id: roberta-large

model:
  name: 'roberta-large'
  batch_size: 128
  lr: 0.01
  num_epochs: 2
  dropout_prob: 0.2
  max_length: 100
  max_epochs: 5
  base_model_require_grad: True
  dataloader_workers: 7
  use_batchsize_finder: False
  use_lr_finder: False
  use_device_stats: False
  save_name: 'roberta-large'

testing:
  test_input_path: '../data/csv/raw_test.csv'
  model_checkpoint: './saved_models/roberta-large.ckpt'